### ISSUE TITLE
Makefile.cesm doesn't work correctly with NETCDF_SEPARATE true

### ISSUE THREAD

**Issue by gdicker1** [ESCOMP/FMS_interface#3]
If NETCDF is split into C and Fortran versions, the variable NETCDF_PATH isn't set and an error occurs near line 159 when the commands `FFLAGS += -I$(INC_NETCDF)` and `CFLAGS += -I(INC_NETCDF)` are issued. This causes a blank `-I` argument, which errors.

**Comment by gdicker1** [comment]
This issue still exists as of this post. It would be best to put an if statement depending on whether NETCDF_SEPARATE is true or not.

**Comment by mnlevy1981** [comment]
This issue still persists, and can be fixed with

```diff
diff --git a/Makefile.cesm b/Makefile.cesm
index cb0ae6f..5b3c03c 100644
--- a/Makefile.cesm
+++ b/Makefile.cesm
@@ -172,8 +172,13 @@ else
   endif
   endif
 endif
+ifeq ($(NETCDF_SEPARATE), false)
   FFLAGS += -I$(INC_NETCDF)
   CFLAGS += -I$(INC_NETCDF)
+else
+  FFLAGS += -I$(INC_NETCDF_FORTRAN)
+  CFLAGS += -I$(INC_NETCDF_C)
+endif

 # Set HAVE_SLASHPROC on LINUX systems which are not bluegene or Darwin (OSx)
```

**Comment by jedwards4b** [comment]
@mnlevy1981 thanks. Can you open a PR with your fix?

**Comment by mnlevy1981** [comment]
It's already there: #23
